/** *****************************************************************************
 * \file    hrtimer_conf.h
 * \brief   Configurations file for hrtimer.c
 *
 * \section AUTHOR
 *    1. Dominik Beinlich
 *
 * \section SVN
 *  $Date$
 *  $Author$
 *  $Revision$
 *
 * \section LICENSE
 * Copyright (c) 2016 Delta Electronics (Hangzhou Design Center & Thailand)
 * All rights reserved.
 ***************************************************************************** */

#ifndef HRTIMER_CONF_H
#define HRTIMER_CONF_H
#ifdef __cplusplus
  extern "C"  {
#endif

/*******************************************************************************
 * Included header
 ******************************************************************************/

#include "global.h"

/*******************************************************************************
 * Local constants and macros (private to module)
 ******************************************************************************/
#define MG_HRTIM_PRESCALER_MUL32        32
#define MG_HRTIM_PRESCALER_MUL16        16
#define MG_HRTIM_PRESCALER_MUL8         8
#define MG_HRTIM_PRESCALER_MUL4         4

#define MG_HRTIM_DTPRESCALER_MUL1       1
#define MG_HRTIM_DTPRESCALER_MUL2       2
#define MG_HRTIM_DTPRESCALER_MUL4       4
#define MG_HRTIM_DTPRESCALER_MUL8       8
#define MG_HRTIM_DTPRESCALER_MUL16      16
#define MG_HRTIM_DTPRESCALER_MUL32      32
#define MG_HRTIM_DTPRESCALER_MUL64      64
#define MG_HRTIM_DTPRESCALER_MUL128     128

/*
 * Set the HRTIMER prescalers.
 * Possible options are:
 * 32 -> fHRCK: 4.608 GHz - Resolution: 217 ps - Min PWM frequency: 70.3 kHz (fHRTIM=144MHz)
 * 16 -> fHRCK: 2.304 GHz - Resolution: 434 ps - Min PWM frequency: 35.1 KHz (fHRTIM=144MHz)
 *  8 -> fHRCK: 1.152 GHz - Resolution: 868 ps - Min PWM frequency: 17.6 kHz (fHRTIM=144MHz)
 *  4 -> fHRCK: 576 MHz - Resolution: 1.73 ns - Min PWM frequency: 8.8 kHz (fHRTIM=144MHz)
 */
#define MG_HRTIM_MST_PRESCALER          MG_HRTIM_PRESCALER_MUL16
#define MG_HRTIM_A_PRESCALER            MG_HRTIM_PRESCALER_MUL16
#define MG_HRTIM_B_PRESCALER            MG_HRTIM_PRESCALER_MUL16
#define MG_HRTIM_C_PRESCALER            MG_HRTIM_PRESCALER_MUL32
#define MG_HRTIM_D_PRESCALER            MG_HRTIM_PRESCALER_MUL32
#define MG_HRTIM_E_PRESCALER            MG_HRTIM_PRESCALER_MUL32

/*
 * Set the dead time prescalers.
 * Possible options are:
 *   1 -> tDTx min 0.87 ns, max 0.44 us
 *   2 -> tDTx min 1.74 ns, max 0.89 us
 *   4 -> tDTx min 3.47 ns, max 1.77 us
 *   8 -> tDTx min 6.94 ns, max 3.54 us
 *  16 -> tDTx min 13.89 ns, max 7.10 us
 *  32 -> tDTx min 27.78 ns, max 14.19 us
 *  64 -> tDTx min 55.55 ns, max 28.39 us
 * 128 -> tDTx min 111.10 ns, max 56.77 us
 */
#define MG_HRTIM_A_DEADTIMPRESCALER     MG_HRTIM_DTPRESCALER_MUL1
#define MG_HRTIM_B_DEADTIMPRESCALER     MG_HRTIM_DTPRESCALER_MUL1
#define MG_HRTIM_C_DEADTIMPRESCALER     MG_HRTIM_DTPRESCALER_MUL1
#define MG_HRTIM_D_DEADTIMPRESCALER     MG_HRTIM_DTPRESCALER_MUL1
#define MG_HRTIM_E_DEADTIMPRESCALER     MG_HRTIM_DTPRESCALER_MUL1

/*******************************************************************************
 * General purpose section
 ******************************************************************************/

#if (MG_HRTIM_MST_PRESCALER == MG_HRTIM_PRESCALER_MUL32)
#define HRTIM_MST_PRESCALERRATIO        HRTIM_PRESCALERRATIO_MUL32
#endif
#if (MG_HRTIM_MST_PRESCALER == MG_HRTIM_PRESCALER_MUL16)
#define HRTIM_MST_PRESCALERRATIO        HRTIM_PRESCALERRATIO_MUL16
#endif
#if (MG_HRTIM_MST_PRESCALER == MG_HRTIM_PRESCALER_MUL8)
#define HRTIM_MST_PRESCALERRATIO        HRTIM_PRESCALERRATIO_MUL8
#endif
#if (MG_HRTIM_MST_PRESCALER == MG_HRTIM_PRESCALER_MUL4)
#define HRTIM_MST_PRESCALERRATIO        HRTIM_PRESCALERRATIO_MUL4
#endif

#if (MG_HRTIM_A_PRESCALER == MG_HRTIM_PRESCALER_MUL32)
#define HRTIM_A_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL32
#endif
#if (MG_HRTIM_A_PRESCALER == MG_HRTIM_PRESCALER_MUL16)
#define HRTIM_A_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL16
#endif
#if (MG_HRTIM_A_PRESCALER == MG_HRTIM_PRESCALER_MUL8)
#define HRTIM_A_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL8
#endif
#if (MG_HRTIM_A_PRESCALER == MG_HRTIM_PRESCALER_MUL4)
#define HRTIM_A_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL4
#endif

#if (MG_HRTIM_B_PRESCALER == MG_HRTIM_PRESCALER_MUL32)
#define HRTIM_B_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL32
#endif
#if (MG_HRTIM_B_PRESCALER == MG_HRTIM_PRESCALER_MUL16)
#define HRTIM_B_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL16
#endif
#if (MG_HRTIM_B_PRESCALER == MG_HRTIM_PRESCALER_MUL8)
#define HRTIM_B_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL8
#endif
#if (MG_HRTIM_B_PRESCALER == MG_HRTIM_PRESCALER_MUL4)
#define HRTIM_B_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL4
#endif

#if (MG_HRTIM_C_PRESCALER == MG_HRTIM_PRESCALER_MUL32)
#define HRTIM_C_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL32
#endif
#if (MG_HRTIM_C_PRESCALER == MG_HRTIM_PRESCALER_MUL16)
#define HRTIM_C_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL16
#endif
#if (MG_HRTIM_C_PRESCALER == MG_HRTIM_PRESCALER_MUL8)
#define HRTIM_C_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL8
#endif
#if (MG_HRTIM_C_PRESCALER == MG_HRTIM_PRESCALER_MUL4)
#define HRTIM_C_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL4
#endif

#if (MG_HRTIM_D_PRESCALER == MG_HRTIM_PRESCALER_MUL32)
#define HRTIM_D_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL32
#endif
#if (MG_HRTIM_D_PRESCALER == MG_HRTIM_PRESCALER_MUL16)
#define HRTIM_D_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL16
#endif
#if (MG_HRTIM_D_PRESCALER == MG_HRTIM_PRESCALER_MUL8)
#define HRTIM_D_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL8
#endif
#if (MG_HRTIM_D_PRESCALER == MG_HRTIM_PRESCALER_MUL4)
#define HRTIM_D_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL4
#endif

#if (MG_HRTIM_E_PRESCALER == MG_HRTIM_PRESCALER_MUL32)
#define HRTIM_E_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL32
#endif
#if (MG_HRTIM_E_PRESCALER == MG_HRTIM_PRESCALER_MUL16)
#define HRTIM_E_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL16
#endif
#if (MG_HRTIM_E_PRESCALER == MG_HRTIM_PRESCALER_MUL8)
#define HRTIM_E_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL8
#endif
#if (MG_HRTIM_E_PRESCALER == MG_HRTIM_PRESCALER_MUL4)
#define HRTIM_E_PRESCALERRATIO          HRTIM_PRESCALERRATIO_MUL4
#endif

#define MG_U8_HRTIM_MST_CLK_PRESCALER   ((uint8)(2 * MG_HRTIM_MST_PRESCALER))
#define MG_U8_HRTIM_A_CLK_PRESCALER     ((uint8)(2 * MG_HRTIM_A_PRESCALER))
#define MG_U8_HRTIM_B_CLK_PRESCALER     ((uint8)(2 * MG_HRTIM_B_PRESCALER))
#define MG_U8_HRTIM_C_CLK_PRESCALER     ((uint8)(2 * MG_HRTIM_C_PRESCALER))
#define MG_U8_HRTIM_D_CLK_PRESCALER     ((uint8)(2 * MG_HRTIM_D_PRESCALER))
#define MG_U8_HRTIM_E_CLK_PRESCALER     ((uint8)(2 * MG_HRTIM_E_PRESCALER))

#if (MG_HRTIM_A_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL1)
#define MG_HRTIM_A_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL1
#endif
#if (MG_HRTIM_A_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL2)
#define MG_HRTIM_A_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL2
#endif
#if (MG_HRTIM_A_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL4)
#define MG_HRTIM_A_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL4
#endif
#if (MG_HRTIM_A_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL8)
#define MG_HRTIM_A_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL8
#endif
#if (MG_HRTIM_A_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL16)
#define MG_HRTIM_A_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL16
#endif
#if (MG_HRTIM_A_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL32)
#define MG_HRTIM_A_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL32
#endif
#if (MG_HRTIM_A_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL64)
#define MG_HRTIM_A_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL64
#endif
#if (MG_HRTIM_A_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL128)
#define MG_HRTIM_A_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL128
#endif

#if (MG_HRTIM_B_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL1)
#define MG_HRTIM_B_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL1
#endif
#if (MG_HRTIM_B_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL2)
#define MG_HRTIM_B_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL2
#endif
#if (MG_HRTIM_B_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL4)
#define MG_HRTIM_B_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL4
#endif
#if (MG_HRTIM_B_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL8)
#define MG_HRTIM_B_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL8
#endif
#if (MG_HRTIM_B_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL16)
#define MG_HRTIM_B_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL16
#endif
#if (MG_HRTIM_B_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL32)
#define MG_HRTIM_B_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL32
#endif
#if (MG_HRTIM_B_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL64)
#define MG_HRTIM_B_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL64
#endif
#if (MG_HRTIM_B_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL128)
#define MG_HRTIM_B_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL128
#endif

#if (MG_HRTIM_C_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL1)
#define MG_HRTIM_C_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL1
#endif
#if (MG_HRTIM_C_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL2)
#define MG_HRTIM_C_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL2
#endif
#if (MG_HRTIM_C_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL4)
#define MG_HRTIM_C_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL4
#endif
#if (MG_HRTIM_C_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL8)
#define MG_HRTIM_C_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL8
#endif
#if (MG_HRTIM_C_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL16)
#define MG_HRTIM_C_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL16
#endif
#if (MG_HRTIM_C_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL32)
#define MG_HRTIM_C_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL32
#endif
#if (MG_HRTIM_C_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL64)
#define MG_HRTIM_C_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL64
#endif
#if (MG_HRTIM_C_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL128)
#define MG_HRTIM_C_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL128
#endif

#if (MG_HRTIM_D_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL1)
#define MG_HRTIM_D_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL1
#endif
#if (MG_HRTIM_D_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL2)
#define MG_HRTIM_D_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL2
#endif
#if (MG_HRTIM_D_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL4)
#define MG_HRTIM_D_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL4
#endif
#if (MG_HRTIM_D_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL8)
#define MG_HRTIM_D_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL8
#endif
#if (MG_HRTIM_D_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL16)
#define MG_HRTIM_D_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL16
#endif
#if (MG_HRTIM_D_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL32)
#define MG_HRTIM_D_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL32
#endif
#if (MG_HRTIM_D_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL64)
#define MG_HRTIM_D_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL64
#endif
#if (MG_HRTIM_D_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL128)
#define MG_HRTIM_D_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL128
#endif

#if (MG_HRTIM_E_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL1)
#define MG_HRTIM_E_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL1
#endif
#if (MG_HRTIM_E_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL2)
#define MG_HRTIM_E_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL2
#endif
#if (MG_HRTIM_E_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL4)
#define MG_HRTIM_E_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL4
#endif
#if (MG_HRTIM_E_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL8)
#define MG_HRTIM_E_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL8
#endif
#if (MG_HRTIM_E_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL16)
#define MG_HRTIM_E_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL16
#endif
#if (MG_HRTIM_E_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL32)
#define MG_HRTIM_E_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL32
#endif
#if (MG_HRTIM_E_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL64)
#define MG_HRTIM_E_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL64
#endif
#if (MG_HRTIM_E_DEADTIMPRESCALER == MG_HRTIM_DTPRESCALER_MUL128)
#define MG_HRTIM_E_DTPRESCALERRATIO     HRTIM_DEADTIMPRESCALERRATIO_MUL128
#endif

#define MG_U16_HRTIM_A_DT_PRESCALER    ((uint16)(16 / MG_HRTIM_A_DEADTIMPRESCALER))  /* fHRTM * 2 * 64 / 8 * DT_prescaler -> fHRTM * 8 * DT_prescaler */
#define MG_U16_HRTIM_B_DT_PRESCALER    ((uint16)(16 / MG_HRTIM_B_DEADTIMPRESCALER))
#define MG_U16_HRTIM_C_DT_PRESCALER    ((uint16)(16 / MG_HRTIM_C_DEADTIMPRESCALER))
#define MG_U16_HRTIM_D_DT_PRESCALER    ((uint16)(16 / MG_HRTIM_D_DEADTIMPRESCALER))
#define MG_U16_HRTIM_E_DT_PRESCALER    ((uint16)(16 / MG_HRTIM_E_DEADTIMPRESCALER))

/* Registers */
#define MG_REG_PWM_A_ON                 HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TA1 | HRTIM_OUTPUT_TA2)
#define MG_REG_PWM_A_OFF                HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TA1 | HRTIM_OUTPUT_TA2)
#define MG_REG_PWM_B_ON                 HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TB1 | HRTIM_OUTPUT_TB2)
#define MG_REG_PWM_B_OFF                HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TB1 | HRTIM_OUTPUT_TB2)
#define MG_REG_PWM_C_ON                 HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TC1 | HRTIM_OUTPUT_TC2)
#define MG_REG_PWM_C_OFF                HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TC1 | HRTIM_OUTPUT_TC2)
#define MG_REG_PWM_D_ON                 HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TD1 | HRTIM_OUTPUT_TD2)
#define MG_REG_PWM_D_OFF                HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TD1 | HRTIM_OUTPUT_TD2)
#define MG_REG_PWM_E_ON                 HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TE1 | HRTIM_OUTPUT_TE2)
#define MG_REG_PWM_E_OFF                HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TE1 | HRTIM_OUTPUT_TE2)

#define MG_REG_PWM_TA1_ON               HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TA1)
#define MG_REG_PWM_TA1_OFF              HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TA1)
#define MG_REG_PWM_TA2_ON               HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TA2)
#define MG_REG_PWM_TA2_OFF              HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TA2)
#define MG_REG_PWM_TB1_ON               HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TB1)
#define MG_REG_PWM_TB1_OFF              HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TB1)
#define MG_REG_PWM_TB2_ON               HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TB2)
#define MG_REG_PWM_TB2_OFF              HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TB2)
#define MG_REG_PWM_TC1_ON               HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TC1)
#define MG_REG_PWM_TC1_OFF              HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TC1)
#define MG_REG_PWM_TC2_ON               HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TC2)
#define MG_REG_PWM_TC2_OFF              HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TC2)
#define MG_REG_PWM_TD1_ON               HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TD1)
#define MG_REG_PWM_TD1_OFF              HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TD1)
#define MG_REG_PWM_TD2_ON               HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TD2)
#define MG_REG_PWM_TD2_OFF              HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TD2)
#define MG_REG_PWM_TE1_ON               HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TE1)
#define MG_REG_PWM_TE1_OFF              HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TE1)
#define MG_REG_PWM_TE2_ON               HRTIM1->HRTIM_COMMON.OENR |= (HRTIM_OUTPUT_TE2)
#define MG_REG_PWM_TE2_OFF              HRTIM1->HRTIM_COMMON.DISR |= (HRTIM_OUTPUT_TE2)

#define MG_REG_HRTIMER1_MST_UPDATE_EN   HRTIM1->HRTIM_COMMON.CR1 &= ~(HRTIM_CR1_MUDIS)
#define MG_REG_HRTIMER1_MST_UPDATE_DIS  HRTIM1->HRTIM_COMMON.CR1 |= (HRTIM_CR1_MUDIS)
#define MG_REG_HRTIMER1_A_UPDATE_EN     HRTIM1->HRTIM_COMMON.CR1 &= ~(HRTIM_CR1_TAUDIS)
#define MG_REG_HRTIMER1_A_UPDATE_DIS    HRTIM1->HRTIM_COMMON.CR1 |= (HRTIM_CR1_TAUDIS)
#define MG_REG_HRTIMER1_B_UPDATE_EN     HRTIM1->HRTIM_COMMON.CR1 &= ~(HRTIM_CR1_TBUDIS)
#define MG_REG_HRTIMER1_B_UPDATE_DIS    HRTIM1->HRTIM_COMMON.CR1 |= (HRTIM_CR1_TBUDIS)
#define MG_REG_HRTIMER1_C_UPDATE_EN     HRTIM1->HRTIM_COMMON.CR1 &= ~(HRTIM_CR1_TCUDIS)
#define MG_REG_HRTIMER1_C_UPDATE_DIS    HRTIM1->HRTIM_COMMON.CR1 |= (HRTIM_CR1_TCUDIS)
#define MG_REG_HRTIMER1_D_UPDATE_EN     HRTIM1->HRTIM_COMMON.CR1 &= ~(HRTIM_CR1_TDUDIS)
#define MG_REG_HRTIMER1_D_UPDATE_DIS    HRTIM1->HRTIM_COMMON.CR1 |= (HRTIM_CR1_TDUDIS)
#define MG_REG_HRTIMER1_E_UPDATE_EN     HRTIM1->HRTIM_COMMON.CR1 &= ~(HRTIM_CR1_TEUDIS)
#define MG_REG_HRTIMER1_E_UPDATE_DIS    HRTIM1->HRTIM_COMMON.CR1 |= (HRTIM_CR1_TEUDIS)

#define MG_REG_HRTIMER1_UPDATE_EN       HRTIM1->HRTIM_COMMON.CR1 &= ~(HRTIM_CR1_TAUDIS | HRTIM_CR1_TBUDIS | HRTIM_CR1_MUDIS)
#define MG_REG_HRTIMER1_UPDATE_DIS      HRTIM1->HRTIM_COMMON.CR1 |= (HRTIM_CR1_TAUDIS | HRTIM_CR1_TBUDIS | HRTIM_CR1_MUDIS)

#define MG_REG_HRTIMER1_A_EN            HRTIM1->HRTIM_MASTER.MCR |= (HRTIM_TIMERID_TIMER_A)
#define MG_REG_HRTIMER1_A_DIS           HRTIM1->HRTIM_MASTER.MCR &= ~(HRTIM_TIMERID_TIMER_A)

#define MG_REG_HRTIMER1_B_EN            HRTIM1->HRTIM_MASTER.MCR |= (HRTIM_TIMERID_TIMER_B)
#define MG_REG_HRTIMER1_B_DIS           HRTIM1->HRTIM_MASTER.MCR &= ~(HRTIM_TIMERID_TIMER_B)

#define MG_REG_HRTIMER1_C_EN            HRTIM1->HRTIM_MASTER.MCR |= (HRTIM_TIMERID_TIMER_C)
#define MG_REG_HRTIMER1_C_DIS           HRTIM1->HRTIM_MASTER.MCR &= ~(HRTIM_TIMERID_TIMER_C)

#define MG_REG_HRTIMER1_D_EN            HRTIM1->HRTIM_MASTER.MCR |= (HRTIM_TIMERID_TIMER_D)
#define MG_REG_HRTIMER1_D_DIS           HRTIM1->HRTIM_MASTER.MCR &= ~(HRTIM_TIMERID_TIMER_D)

#define MG_REG_HRTIMER1_E_EN            HRTIM1->HRTIM_MASTER.MCR |= (HRTIM_TIMERID_TIMER_E)
#define MG_REG_HRTIMER1_E_DIS           HRTIM1->HRTIM_MASTER.MCR &= ~(HRTIM_TIMERID_TIMER_E)

#define MG_REG_HRTIMER1_A_CTR_RST       HRTIM1->HRTIM_COMMON.CR2 = HRTIM_CR2_TARST
#define MG_REG_HRTIMER1_B_CTR_RST       HRTIM1->HRTIM_COMMON.CR2 = HRTIM_CR2_TBRST
#define MG_REG_HRTIMER1_C_CTR_RST       HRTIM1->HRTIM_COMMON.CR2 = HRTIM_CR2_TCRST
#define MG_REG_HRTIMER1_D_CTR_RST       HRTIM1->HRTIM_COMMON.CR2 = HRTIM_CR2_TDRST
#define MG_REG_HRTIMER1_E_CTR_RST       HRTIM1->HRTIM_COMMON.CR2 = HRTIM_CR2_TERST

#define MG_REG_HRTIMER1_MST_CMP1        HRTIM1->HRTIM_MASTER.MCMP1R
#define MG_REG_HRTIMER1_MST_CMP2        HRTIM1->HRTIM_MASTER.MCMP2R
#define MG_REG_HRTIMER1_MST_CMP3        HRTIM1->HRTIM_MASTER.MCMP3R
#define MG_REG_HRTIMER1_MST_CMP4        HRTIM1->HRTIM_MASTER.MCMP4R

#define MG_REG_HRTIMER1_A_CMP1          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_A].CMP1xR
#define MG_REG_HRTIMER1_A_CMP2          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_A].CMP2xR
#define MG_REG_HRTIMER1_A_CMP3          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_A].CMP3xR
#define MG_REG_HRTIMER1_A_CMP4          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_A].CMP4xR

#define MG_REG_HRTIMER1_B_CMP1          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_B].CMP1xR
#define MG_REG_HRTIMER1_B_CMP2          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_B].CMP2xR
#define MG_REG_HRTIMER1_B_CMP3          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_B].CMP3xR
#define MG_REG_HRTIMER1_B_CMP4          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_B].CMP4xR

#define MG_REG_HRTIMER1_C_CMP1          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_C].CMP1xR
#define MG_REG_HRTIMER1_C_CMP2          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_C].CMP2xR
#define MG_REG_HRTIMER1_C_CMP3          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_C].CMP3xR
#define MG_REG_HRTIMER1_C_CMP4          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_C].CMP4xR

#define MG_REG_HRTIMER1_D_CMP1          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_D].CMP1xR
#define MG_REG_HRTIMER1_D_CMP2          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_D].CMP2xR
#define MG_REG_HRTIMER1_D_CMP3          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_D].CMP3xR
#define MG_REG_HRTIMER1_D_CMP4          HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_D].CMP4xR

#define MG_REG_HRTIMER1_MST_PERIOD      HRTIM1->HRTIM_MASTER.MPER
#define MG_REG_HRTIMER1_A_PERIOD        HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_A].PERxR
#define MG_REG_HRTIMER1_B_PERIOD        HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_B].PERxR
#define MG_REG_HRTIMER1_C_PERIOD        HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_C].PERxR
#define MG_REG_HRTIMER1_D_PERIOD        HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_D].PERxR
#define MG_REG_HRTIMER1_E_PERIOD        HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_E].PERxR

#define MG_REG_HRTIMER1_A_DT_R(var)     HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_A].DTxR = ((HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_A].DTxR & 0xFFFFFE00) + var)
#define MG_REG_HRTIMER1_A_DT_F(var)     HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_A].DTxR = ((HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_A].DTxR & 0xFE00FFFF) + (var << 16))
#define MG_REG_HRTIMER1_B_DT_R(var)     HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_B].DTxR = ((HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_B].DTxR & 0xFFFFFE00) + var)
#define MG_REG_HRTIMER1_B_DT_F(var)     HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_B].DTxR = ((HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_B].DTxR & 0xFE00FFFF) + (var << 16))
#define MG_REG_HRTIMER1_C_DT_R(var)     HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_C].DTxR = ((HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_C].DTxR & 0xFFFFFE00) + var)
#define MG_REG_HRTIMER1_C_DT_F(var)     HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_C].DTxR = ((HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_C].DTxR & 0xFE00FFFF) + (var << 16))
#define MG_REG_HRTIMER1_D_DT_R(var)     HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_D].DTxR = ((HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_D].DTxR & 0xFFFFFE00) + var)
#define MG_REG_HRTIMER1_D_DT_F(var)     HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_D].DTxR = ((HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_D].DTxR & 0xFE00FFFF) + (var << 16))
#define MG_REG_HRTIMER1_E_DT_R(var)     HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_E].DTxR = ((HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_E].DTxR & 0xFFFFFE00) + var)
#define MG_REG_HRTIMER1_E_DT_F(var)     HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_E].DTxR = ((HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_E].DTxR & 0xFE00FFFF) + (var << 16))

#define MG_REG_HRTIMER1_FAULT1          HRTIM1->HRTIM_COMMON.ISR & HRTIM_FAULT_1
#define MG_REG_HRTIMER1_FAULT2          HRTIM1->HRTIM_COMMON.ISR & HRTIM_FAULT_2
#define MG_REG_HRTIMER1_FAULT3          HRTIM1->HRTIM_COMMON.ISR & HRTIM_FAULT_3
#define MG_REG_HRTIMER1_FAULT4          HRTIM1->HRTIM_COMMON.ISR & HRTIM_FAULT_4
#define MG_REG_HRTIMER1_FAULT5          HRTIM1->HRTIM_COMMON.ISR & HRTIM_FAULT_5

#define MG_REG_HRTIMER1_FAULT1_CLR      HRTIM1->HRTIM_COMMON.ICR = HRTIM_FAULT_1
#define MG_REG_HRTIMER1_FAULT2_CLR      HRTIM1->HRTIM_COMMON.ICR = HRTIM_FAULT_2
#define MG_REG_HRTIMER1_FAULT3_CLR      HRTIM1->HRTIM_COMMON.ICR = HRTIM_FAULT_3
#define MG_REG_HRTIMER1_FAULT4_CLR      HRTIM1->HRTIM_COMMON.ICR = HRTIM_FAULT_4
#define MG_REG_HRTIMER1_FAULT5_CLR      HRTIM1->HRTIM_COMMON.ICR = HRTIM_FAULT_5

#define MG_REG_HRTIMER1_A_DLYPROT       (HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_A].TIMxISR & HRTIM_TIM_IT_DLYPRT) != 0
#define MG_REG_HRTIMER1_A_DLYPROT_CLR   HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_A].TIMxICR |= HRTIM_TIM_FLAG_DLYPRT1
#define MG_REG_HRTIMER1_B_DLYPROT       (HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_B].TIMxISR & HRTIM_TIM_IT_DLYPRT) != 0
#define MG_REG_HRTIMER1_B_DLYPROT_CLR   HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_B].TIMxICR |= HRTIM_TIM_FLAG_DLYPRT1
#define MG_REG_HRTIMER1_C_DLYPROT       (HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_C].TIMxISR & HRTIM_TIM_IT_DLYPRT) != 0
#define MG_REG_HRTIMER1_C_DLYPROT_CLR   HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_C].TIMxICR |= HRTIM_TIM_FLAG_DLYPRT1
#define MG_REG_HRTIMER1_D_DLYPROT       (HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_D].TIMxISR & HRTIM_TIM_IT_DLYPRT) != 0
#define MG_REG_HRTIMER1_D_DLYPROT_CLR   HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_D].TIMxICR |= HRTIM_TIM_FLAG_DLYPRT1
#define MG_REG_HRTIMER1_E_DLYPROT       (HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_E].TIMxISR & HRTIM_TIM_IT_DLYPRT) != 0
#define MG_REG_HRTIMER1_E_DLYPROT_CLR   HRTIM1->HRTIM_TIMERx[HRTIM_TIMERINDEX_TIMER_E].TIMxICR |= HRTIM_TIM_FLAG_DLYPRT1

#define MG_REG_HRTIMER1_MST_REP_IR_CLR  HRTIM1->HRTIM_MASTER.MICR |= HRTIM_MISR_MREP;
#define MG_REG_HRTIMER1_MST_CMP1_IR_CLR HRTIM1->HRTIM_MASTER.MICR |= HRTIM_MASTER_FLAG_MCMP1;
#define MG_REG_HRTIMER1_MST_CMP2_IR_CLR HRTIM1->HRTIM_MASTER.MICR |= HRTIM_MASTER_FLAG_MCMP2;
#define MG_REG_HRTIMER1_MST_CMP3_IR_CLR HRTIM1->HRTIM_MASTER.MICR |= HRTIM_MASTER_FLAG_MCMP3;
#define MG_REG_HRTIMER1_MST_CMP4_IR_CLR HRTIM1->HRTIM_MASTER.MICR |= HRTIM_MASTER_FLAG_MCMP4;

#define MG_REG_HRTIMER1_MST_REP_IR_RD   HRTIM1->HRTIM_MASTER.MISR & HRTIM_MISR_MREP;
#define MG_REG_HRTIMER1_MST_CMP1_IR_RD  HRTIM1->HRTIM_MASTER.MISR & HRTIM_MASTER_FLAG_MCMP1;
#define MG_REG_HRTIMER1_MST_CMP2_IR_RD  HRTIM1->HRTIM_MASTER.MISR & HRTIM_MASTER_FLAG_MCMP2;
#define MG_REG_HRTIMER1_MST_CMP3_IR_RD  HRTIM1->HRTIM_MASTER.MISR & HRTIM_MASTER_FLAG_MCMP3;
#define MG_REG_HRTIMER1_MST_CMP4_IR_RD  HRTIM1->HRTIM_MASTER.MISR & HRTIM_MASTER_FLAG_MCMP4;

#define MG_HRTIMER1_MASTER_UPDATE       (0x1U << 0)
#define MG_HRTIMER1_A_UPDATE            (0x1U << 1)
#define MG_HRTIMER1_B_UPDATE            (0x1U << 2)
#define MG_HRTIMER1_C_UPDATE            (0x1U << 3)
#define MG_HRTIMER1_D_UPDATE            (0x1U << 4)
#define MG_HRTIMER1_E_UPDATE            (0x1U << 5)

/***************************************
 * HrTimer ID config
 **************************************/
#define MG_HRTIM_MST    0
#define MG_HRTIM_A      1
#define MG_HRTIM_B      2
#define MG_HRTIM_C      3
#define MG_HRTIM_D      4
#define MG_HRTIM_E      5

/*******************************************************************************
 * Global data (public to other modules)
 ******************************************************************************/

#if defined(HRTIMER_EXPORT_H)
  #define EXTERN
#else
  #define EXTERN extern
#endif

EXTERN uint32 mg_u32q12nsTimerMstConvFact;
EXTERN uint32 mg_u32q12nsTimerAConvFact;
EXTERN uint32 mg_u32q12nsTimerBConvFact;
EXTERN uint32 mg_u32q12nsTimerCConvFact;
EXTERN uint32 mg_u32q12nsTimerDConvFact;
EXTERN uint32 mg_u32q12nsTimerEConvFact;
EXTERN uint32 mg_u32q12nsTimerADtConvFact;
EXTERN uint32 mg_u32q12nsTimerBDtConvFact;
EXTERN uint32 mg_u32q12nsTimerCDtConvFact;
EXTERN uint32 mg_u32q12nsTimerDDtConvFact;
EXTERN uint32 mg_u32q12nsTimerEDtConvFact;


#ifdef __cplusplus
  }
#endif
#endif  /* HRTIMER_CONF_H */

  
/*
 * End of file
 */
